[package]
name = "msg_templates"
version = "0.1.1"
edition = "2021"
description = "A library to store data with a format into strings."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnpkg = { path = "../lnpkg" }
